exec(open("C:\QA_paths\set_QA_paths.py").read())

import sqlite3

def main():
    def setDirectory():
        # default path for DB.
        database = 'ELOG.db'

        print("Would you like to change database location?")
        print(" Current path: " + database + "\n y/n")
        select = input()
        if select.lower() == "y":
            print("Input new path:")
            database = input()
            print("\nNew Path: " + database + "\n")
            return database
        elif select.lower() == "n":
            return database
        else:
            print("Please Choose y or n...\n")
            setDirectory()

    database = setDirectory()
    conn = sqlite3.connect(database)
    c = conn.cursor()

    # Table containing all meta data
    create_elog_table = """CREATE TABLE IF NOT EXISTS ELOG(
                                id INTEGER NOT NULL,
                                Date Text,
                                day Text,
                                month Text, 
                                year Text,
                                time Text,
                                timezone Text,
                                Replyto Text,
                                Event Text,
                                Station Text, 
                                Instrument Text,
                                Attached Text,
                                Action Text,
                                Sounding Text,      
                                Sample_ID Text,
                                End_Sample_ID Text,
                                WireOut Text,
                                Depth Text,
                                Author Text,
                                Seq_Number Text,
                                IMEI_No Text,
                                WMO_No Text,
                                SN Text,
                                Name Text,
                                Comment Text, 
                                isoTime Text, 
                                latitude Text,
                                longitude Text, 
                                Lat Text,
                                Lon Text,
                                Cruise Text,
                                PI Text, 
                                Protocol Text,
                                Platform Text,   
                                Revisions Text,
                                Attachment Text,
                                Encoding Text,
                                File Text,
                                PRIMARY KEY (id)
                                );"""

    # Table to keep record of any changes to the data
    create_log_table = """CREATE TABLE ELOGLog(
                                lKey INTEGER PRIMARY KEY,
                                id_old  INTEGER,
                                elog_id INTEGER,
                                Date_old Text,
                                Date_new Text,
                                day_old Text,
                                day_new Text,
                                month_old Text,
                                month_new Text, 
                                year_old Text,
                                year_new Text,
                                time_old Text,
                                time_new Text,
                                timezone_old Text,
                                timezone_new Text,
                                Replyto_old Text,
                                Replyto_new Text,
                                Event_old Text,
                                Event_new Text,
                                Station_old Text,
                                Station_new Text, 
                                Instrument_old Text,
                                Instrument_new Text,
                                Attached_old Text,
                                Attached_new Text,
                                Action_old Text,
                                Action_new Text,
                                Sounding_old Text,
                                Sounding_new Text,      
                                Sample_ID_old Text,
                                Sample_ID_new Text,
                                End_Sample_ID_old Text,
                                End_Sample_ID_new Text,
                                WireOut_old Text,
                                WireOut_new Text,
                                Depth_old Text,
                                Depth_new Text,
                                Author_old Text,
                                Author_new Text,
                                Seq_Number_old Text,
                                Seq_Number_new Text,
                                IMEI_No_old Text,
                                IMEI_No_new Text,
                                WMO_No_old Text,
                                WMO_No_new Text,
                                SN_old Text,
                                SN_new Text,
                                Name_old Text,
                                Name_new Text,
                                Comment_old Text,
                                Comment_new Text, 
                                isoTime_old Text,
                                isoTime_new Text, 
                                latitude_old Text,
                                latitude_new Text,
                                longitude_old Text,
                                longitude_new Text, 
                                Lat_old Text,
                                Lat_new Text,
                                Lon_old Text,
                                Lon_new Text,
                                Cruise_old Text,
                                Cruise_new Text,
                                PI_old Text,
                                PI_new Text, 
                                Protocol_old Text,
                                Protocol_new Text,
                                Platform_old Text,
                                Platform_new Text,   
                                Revisions_old Text,
                                Revisions_new Text,
                                Attachment_old Text,
                                Attachment_new Text,
                                Encoding_old Text,
                                Encoding_new Text,
                                sqlAction VARCHAR(15),
                                Edited DATE,
                                FOREIGN KEY (elog_id) REFERENCES ELOG(id));
                                """

    create_trigger_update = """CREATE TRIGGER update_log AFTER UPDATE ON ELOG
                            BEGIN

                                INSERT INTO ELOGLog(
                                id_old,
                                elog_id,
                                Date_old,
                                Date_new,
                                day_old,
                                day_new,
                                month_old,
                                month_new,
                                year_old,
                                year_new,
                                time_old,
                                time_new,
                                timezone_old,
                                timezone_new,
                                Replyto_old,
                                Replyto_new,
                                Event_old,
                                Event_new,
                                Station_old,
                                Station_new,
                                Instrument_old,
                                Instrument_new,
                                Attached_old,
                                Attached_new,
                                Action_old,
                                Action_new,
                                Sounding_old,
                                Sounding_new,
                                Sample_ID_old,
                                Sample_ID_new,
                                End_Sample_ID_old,
                                End_Sample_ID_new,
                                WireOut_old,
                                WireOut_new,
                                Depth_old,
                                Depth_new,
                                Author_old,
                                Author_new,
                                Seq_Number_old,
                                Seq_Number_new,
                                IMEI_No_old,
                                IMEI_No_new,
                                WMO_No_old,
                                WMO_No_new,
                                SN_old,
                                SN_new,
                                Name_old,
                                Name_new,
                                Comment_old,
                                Comment_new,
                                isoTime_old,
                                isoTime_new,
                                latitude_old,
                                latitude_new,
                                longitude_old,
                                longitude_new,
                                Lat_old,
                                Lat_new,
                                Lon_old,
                                Lon_new,
                                Cruise_old,
                                Cruise_new,
                                PI_old,
                                PI_new,
                                Protocol_old,
                                Protocol_new,
                                Platform_old,
                                Platform_new,
                                Revisions_old,
                                Revisions_new,
                                Attachment_old,
                                Attachment_new,
                                Encoding_old,
                                Encoding_new,
                                sqlAction,
                                Edited)


                                values(       
                                old.id,
                                new.id,
                                old.Date,
                                new.Date,
                                old.day,
                                new.day,
                                old.month,
                                new.month,
                                old.year,
                                new.year,
                                old.time,
                                new.time,
                                old.timezone,
                                new.timezone,
                                old.Replyto,
                                new.Replyto,
                                old.Event,
                                new.Event,
                                old.Station,
                                new.Station,
                                old.Instrument,
                                new.Instrument,
                                old.Attached,
                                new.Attached,
                                old.Action,
                                new.Action,
                                old.Sounding,
                                new.Sounding,
                                old.Sample_ID,
                                new.Sample_ID,
                                old.End_Sample_ID,
                                new.End_Sample_ID,
                                old.WireOut,
                                new.WireOut,
                                old.Depth,
                                new.Depth,
                                old.Author,
                                new.Author,
                                old.Seq_Number,
                                new.Seq_Number,
                                old.IMEI_No,
                                new.IMEI_No,
                                old.WMO_No,
                                new.WMO_No,
                                old.SN,
                                new.SN,
                                old.Name,
                                new.Name,
                                old.Comment,
                                new.Comment,
                                old.isoTime,
                                new.isoTime,
                                old.latitude,
                                new.latitude,
                                old.longitude,
                                new.longitude,
                                old.Lat,
                                new.Lat,
                                old.Lon,
                                new.Lon,
                                old.Cruise,
                                new.Cruise,
                                old.PI,
                                new.PI,
                                old.Protocol,
                                new.Protocol,
                                old.Platform,
                                new.Platform,
                                old.Revisions,
                                new.Revisions,
                                old.Attachment,
                                new.Attachment,
                                old.Encoding,
                                new.Encoding, 
                                'UPDATE',
                                DATETIME('NOW'));
                                END;
                                """

    create_trigger_delete = """CREATE TRIGGER delete_log AFTER DELETE ON ELOG
                            BEGIN

                                INSERT INTO ELOGLog(
                                
                                id_old,
                                elog_id,
                                Date_old,
                                Date_new,
                                day_old,
                                day_new,
                                month_old,
                                month_new,
                                year_old,
                                year_new,
                                time_old,
                                time_new,
                                timezone_old,
                                timezone_new,
                                Replyto_old,
                                Replyto_new,
                                Event_old,
                                Event_new,
                                Station_old,
                                Station_new,
                                Instrument_old,
                                Instrument_new,
                                Attached_old,
                                Attached_new,
                                Action_old,
                                Action_new,
                                Sounding_old,
                                Sounding_new,
                                Sample_ID_old,
                                Sample_ID_new,
                                End_Sample_ID_old,
                                End_Sample_ID_new,
                                WireOut_old,
                                WireOut_new,
                                Depth_old,
                                Depth_new,
                                Author_old,
                                Author_new,
                                Seq_Number_old,
                                Seq_Number_new,
                                IMEI_No_old,
                                IMEI_No_new,
                                WMO_No_old,
                                WMO_No_new,
                                SN_old,
                                SN_new,
                                Name_old,
                                Name_new,
                                Comment_old,
                                Comment_new,
                                isoTime_old,
                                isoTime_new,  
                                latitude_old,
                                latitude_new,
                                longitude_old,
                                longitude_new,
                                Lat_old,
                                Lat_new,
                                Lon_old,
                                Lon_new,
                                Cruise_old,
                                Cruise_new,
                                PI_old,
                                PI_new,
                                Protocol_old,
                                Protocol_new,
                                Platform_old,
                                Platform_new,
                                Revisions_old,
                                Revisions_new,
                                Attachment_old,
                                Attachment_new,
                                Encoding_old,
                                Encoding_new,
                                sqlAction,
                                Edited)

                                values(       
                                old.id,
                                new.id,
                                old.Date,
                                new.Date,
                                old.day,
                                new.day,
                                old.month,
                                new.month,
                                old.year,
                                new.year,
                                old.time,
                                new.time,
                                old.timezone,
                                new.timezone,
                                old.Replyto,
                                new.Replyto,
                                old.Event,
                                new.Event,
                                old.Station,
                                new.Station,
                                old.Instrument,
                                new.Instrument,
                                old.Attached,
                                new.Attached,
                                old.Action,
                                new.Action,
                                old.Sounding,
                                new.Sounding,
                                old.Sample_ID,
                                new.Sample_ID,
                                old.End_Sample_ID,
                                new.End_Sample_ID,
                                old.WireOut,
                                new.WireOut,
                                old.Depth,
                                new.Depth,
                                old.Author,
                                new.Author,
                                old.Seq_Number,
                                new.Seq_Number,
                                old.IMEI_No,
                                new.IMEI_No,
                                old.WMO_No,
                                new.WMO_No,
                                old.SN,
                                new.SN,
                                old.Name,
                                new.Name,
                                old.Comment,
                                new.Comment,
                                old.isoTime,
                                new.isoTime,
                                old.latitude,
                                new.latitude,
                                old.longitude,
                                new.longitude,
                                old.Lat,
                                new.Lat,
                                old.Lon,
                                new.Lon,
                                old.Cruise,
                                new.Cruise,
                                old.PI,
                                new.PI,
                                old.Protocol,
                                new.Protocol,
                                old.Platform,
                                new.Platform,
                                old.Revisions,
                                new.Revisions,
                                old.Attachment,
                                new.Attachment,
                                old.Encoding,
                                new.Encoding, 
                                'UPDATE',
                                DATETIME('NOW'));
                                END;
                                """

    if conn is not None:
        c.execute(create_elog_table)
        c.execute(create_log_table)
        c.execute(create_trigger_update)
        c.execute(create_trigger_delete)
    else:
        print("Error: Cannot Connect To DB.")


if __name__ == '__main__':
    main()
